set(_CATKIN_CURRENT_PACKAGE "zed_obj_det_sub_tutorial")
set(zed_obj_det_sub_tutorial_VERSION "3.0.0")
set(zed_obj_det_sub_tutorial_MAINTAINER "STEREOLABS <support@stereolabs.com>")
set(zed_obj_det_sub_tutorial_PACKAGE_FORMAT "2")
set(zed_obj_det_sub_tutorial_BUILD_DEPENDS "roscpp" "zed_wrapper")
set(zed_obj_det_sub_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "zed_wrapper")
set(zed_obj_det_sub_tutorial_BUILDTOOL_DEPENDS "catkin")
set(zed_obj_det_sub_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(zed_obj_det_sub_tutorial_EXEC_DEPENDS "roscpp" "zed_wrapper")
set(zed_obj_det_sub_tutorial_RUN_DEPENDS "roscpp" "zed_wrapper")
set(zed_obj_det_sub_tutorial_TEST_DEPENDS )
set(zed_obj_det_sub_tutorial_DOC_DEPENDS )
set(zed_obj_det_sub_tutorial_URL_WEBSITE "http://stereolabs.com/")
set(zed_obj_det_sub_tutorial_URL_BUGTRACKER "https://github.com/stereolabs/zed-ros-tutorials/issues")
set(zed_obj_det_sub_tutorial_URL_REPOSITORY "https://github.com/stereolabs/zed-ros-tutorials")
set(zed_obj_det_sub_tutorial_DEPRECATED "")