set(_CATKIN_CURRENT_PACKAGE "zed_sensors_sub_tutorial")
set(zed_sensors_sub_tutorial_VERSION "3.0.0")
set(zed_sensors_sub_tutorial_MAINTAINER "STEREOLABS <support@stereolabs.com>")
set(zed_sensors_sub_tutorial_PACKAGE_FORMAT "2")
set(zed_sensors_sub_tutorial_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(zed_sensors_sub_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(zed_sensors_sub_tutorial_BUILDTOOL_DEPENDS "catkin")
set(zed_sensors_sub_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(zed_sensors_sub_tutorial_EXEC_DEPENDS "zed_wrapper" "roscpp" "sensor_msgs")
set(zed_sensors_sub_tutorial_RUN_DEPENDS "zed_wrapper" "roscpp" "sensor_msgs")
set(zed_sensors_sub_tutorial_TEST_DEPENDS )
set(zed_sensors_sub_tutorial_DOC_DEPENDS )
set(zed_sensors_sub_tutorial_URL_WEBSITE "http://stereolabs.com/")
set(zed_sensors_sub_tutorial_URL_BUGTRACKER "https://github.com/stereolabs/zed-ros-examples/issues")
set(zed_sensors_sub_tutorial_URL_REPOSITORY "https://github.com/stereolabs/zed-ros-examples")
set(zed_sensors_sub_tutorial_DEPRECATED "")